### ISSUE TITLE
_tkinter.TclError: bitmap

### ISSUE THREAD

**Issue by spiderocta** [spiderocta/sqlnoop#1]
```
Traceback (most recent call last):
  File "sqlNoop.py", line 10, in <module>
    root.iconbitmap('images/icon.ico')
  File "/usr/lib/python3.8/tkinter/__init__.py", line 2080, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, bitmap)
_tkinter.TclError: bitmap "images/icon.ico" not defined

```

getting this error after running  `python3 sqlNoop.py `  on linux

**Comment by spiderocta** [comment]
to solve this just comment the `root.iconbitmap('images/icon.ico')` line.
